name: C/C++ CI release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - name: Install R
      uses: r-lib/actions/setup-r@11a22a908006c25fe054c4ef0ac0436b1de3edbe # v2.6.4
      with:
        use-public-rspm: true

    - name: Install dependencies
      run: |
        install.packages("stringr")
        install.packages("Rcpp")
      shell: Rscript {0}

    - name: Install APT Packages
      run: |
          sudo apt-get update &&
          sudo apt-get install -y libopencv-dev &&
          sudo apt-get install -y libfmt-dev

    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Build shared object with RCPP
      run: |
          R CMD SHLIB -c src/matching.cpp
